// Generated by CoffeeScript 1.4.0
(function() {
  var Kennitala, dateToArray, generate, getRandom, validate;

  validate = function(kt) {
    var i, n, x;
    kt = kt.replace(/\s/g, '').replace(/^(\d{6})[\s-]?(\d{4})$/, '$1$2');
    if (kt.length !== 10 || !/[90]$/.test(kt)) {
      return false;
    }
    if (/010130(2(12|20|39|47|55|63|71|98)|3(01|36)|4(33|92)|506|778)9/.test(kt)) {
      return false;
    }
    x = [3, 2, 7, 6, 5, 4, 3, 2, 1].reverse();
    if ((((function() {
      var _i, _len, _ref, _results;
      _ref = kt.split('').reverse().slice(1, 10);
      _results = [];
      for (n = _i = 0, _len = _ref.length; _i < _len; n = ++_i) {
        i = _ref[n];
        _results.push(+i * x[n]);
      }
      return _results;
    })()).reduce(function(x, y) {
      return x + y;
    })) % 11) {
      return false;
    }
    return true;
  };

  getRandom = function() {
    var i, rnd;
    rnd = Math.floor((Math.random() * 99) + 1);
    if (String(rnd.length) === 1) {
      return [0, rnd];
    }
    return (function() {
      var _i, _len, _ref, _results;
      _ref = String(rnd).split('');
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        i = _ref[_i];
        _results.push(+i);
      }
      return _results;
    })();
  };

  dateToArray = function(date) {
    var d, m, stack, yr;
    stack = [];
    d = String(date.getDay());
    stack.push(d.length === 1 ? "0" + d : d);
    m = String(date.getMonth() + 1);
    stack.push(m.length === 1 ? "0" + m : m);
    yr = String(date.getFullYear());
    stack.push(yr.slice(2));
    return stack.join('').split('');
  };

  generate = function(date) {
    var chk, i, kt, n, remainder, rnd, stack, sum, valid, _i, _len, _ref;
    stack = dateToArray(date);
    valid = false;
    while (!valid) {
      rnd = getRandom();
      kt = ((function() {
        var _i, _len, _ref, _results;
        _ref = stack.join('');
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          i = _ref[_i];
          _results.push(+i);
        }
        return _results;
      })()).concat(rnd);
      sum = 0;
      _ref = [2, 3, 4, 5, 6, 7, 2, 3].reverse();
      for (n = _i = 0, _len = _ref.length; _i < _len; n = ++_i) {
        i = _ref[n];
        sum += kt[n] * i;
      }
      remainder = sum % 11;
      chk = 11 - remainder;
      if (remainder === 0) {
        chk = 0;
      }
      if (chk < 10) {
        stack.push(rnd.join(''));
        stack.push(chk);
        stack.push(String(date.getFullYear())[1]);
        valid = true;
      }
    }
    return stack.join('');
  };

  Kennitala = (typeof exports !== "undefined" && exports !== null) && exports || (this.Kennitala = {});

  Kennitala.validate = validate;

  Kennitala.generate = generate;

}).call(this);
